(defun sum-of-bigger-two-numbers (a b c)
  (cond ((and (>= a b) (>= b c)) (+ a b))
	((and (>= a c) (>= c b)) (+ a c))
	((and (>= b a) (>= a c)) (+ b a))
	((and (>= b c) (>= c a)) (+ b c))
	((and (>= c a) (>= a b)) (+ c a))
	((and (>= c b) (>= b a)) (+ c b))))
(sum-of-bigger-two-numbers 3 2 3)
