(defun A (x y)
  (cond ((= y 0) 0)
	((= x 0) (* 2 y))
	((= y 1) 2)
	(t (A (- x 1)
	      (A x (- y 1))))))

(A 1 10)
(A 2 4)
(A 3 3)

(defun f (n) (A 0 n))
(defun g (n) (A 1 n))
(defun h (n) (A 2 n))
(defun k (n) (* 5 n n ))
