syntax on
set hlsearch
set mouse=nv
set cindent
set incsearch
filetype plugin indent on
colorscheme default
map grep :grep -InR "\<<cword>\>" *<CR><CR>:cw<CR>
set helplang=cn
let &termencoding=&encoding
set fileencodings=utf-8,gbk,cp936
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set expandtab
set softtabstop=4
set hidden

" man 3 
map K :!man 3 <C-R>=expand("<cword>")<CR><CR>

set completeopt=menu,menuone

" SuperTab option for context aware completion
"let g:SuperTabDefaultCompletionType='context'

" SuperTab option for context aware completion fall back
"let g:SuperTabContextDefaultCompletionType='<c-x><c-o>'

"----- for clang -----
let g:clang_snippets=1
let g:clang_snippets_engine='ultisnips'

"----- for YCM -----
"let g:ycm_confirm_extra_conf = 0
"map <C-]> :YcmCompleter GoToDefinitionElseDeclaration<CR>
"nmap <C-\> :YcmForceCompileAndDiagnostics<CR>
"imap <C-\> <ESC>:YcmForceCompileAndDiagnostics<CR>

"----- for syntastic -----
let g:syntastic_error_symbol='ER'
let g:syntastic_warning_symbol='WA'
let g:syntastic_c_compiler='clang'
"let g:syntastic_c_compiler_options = '-nostdinc -nostdlibinc -nobuiltininc'


" --- for qy ---
map <C-K> 5
map <C-J> 5
map . <C-K>
map , <C-J>

" map <F1> same as ESC
nmap <F1> <ESC>
imap <F1> <ESC>

" Window Manager
"let g:winManagerWindowLayout='TagList|FileExplorer'
let g:winManagerWindowLayout='FileExplorer'
nmap wm :WMToggle<cr>

" Tag list
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

" for TinyOS
map tos :!ctags $TOSCTAGS<CR><CR>

function TosSignatureModule()
	call setline(1,"/*")
	call append(1, " * ".expand("%<"))
	call append(2, " *")
	call append(3, " * @author Qiu Ying <qiuying@mail.nwpu.edu.cn>")
	call append(4, " * @date ".strftime("%Y/%m/%d"))
	call append(5, " * @description")
	call append(6, " */")
	call append(7, "module ".expand("%<")." {")
	call append(8, "}")
	call append(9, "implementation {")
	call append(10, "}")
	endf
function TosSignatureConfigure()
	call setline(1,"/*")
	call append(1, " * ".expand("%<"))
	call append(2, " *")
	call append(3, " * @author Qiu Ying <qiuying@mail.nwpu.edu.cn>")
	call append(4, " * @date ".strftime("%Y/%m/%d"))
	call append(5, " * @description")
	call append(6, " */")
	call append(7, "configuration ".expand("%<")." {")
	call append(8, "}")
	call append(9, "implementation {")
	call append(10, "}")
	endf
function TosSignatureInterface()
	call setline(1,"/*")
	call append(1, " * ".expand("%<"))
	call append(2, " *")
	call append(3, " * @author Qiu Ying <qiuying@mail.nwpu.edu.cn>")
	call append(4, " * @date ".strftime("%Y/%m/%d"))
	call append(5, " * @description")
	call append(6, " */")
	call append(7, "interface ".expand("%<")." {")
	call append(8, "}")
	endf

function Qytitle()
	call setline(1,"/*")
	call append(1, " * ".expand("%<"))
	call append(2, " *")
	call append(3, " * @author Qiu Ying <qiuying@mail.nwpu.edu.cn>")
	call append(4, " * @date ".strftime("%Y/%m/%d"))
	call append(5, " * @description")
	call append(6, " */")
endf
function Geeeqie()
	call setline(1,"/*")
	call append(1, " * ".expand("%<"))
	call append(2, " *")
	call append(3, " * @author Geeeqie <geeeqie@gmail.com>")
	call append(4, " * @date ".strftime("%Y/%m/%d"))
	call append(5, " * @description")
	call append(6, " */")
endf
map qy :call Qytitle()<CR>
map gq :call Geeeqie()<CR>
map conf :call TosSignatureConfigure()<CR>
map mod :call TosSignatureModule()<CR>
map int :call TosSignatureInterface()<CR>

